# Generated by Django 3.1.1 on 2020-09-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.AlterField(
            model_name='profile',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='profile',
            table='Profile',
        ),
    ]
