# Generated by Django 3.1.1 on 2020-09-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_post_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main_image',
            field=models.ImageField(default='', upload_to='auction/images'),
            preserve_default=False,
        ),
    ]
