# Generated by Django 3.1.1 on 2020-11-26 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0006_auto_20201125_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bought_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bought_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
