# Generated by Django 3.1.1 on 2020-11-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_post_bought_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='available_till',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время, до которого лот можно купить'),
        ),
    ]
